doctrine:
  dbal:
    # Utilisez le nom de la base de données "tomoki" directement dans l'URL
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: Vous pouvez configurer ici la version de votre serveur si nécessaire
    # server_version: '16'

    profiling_collect_backtrace: "%kernel.debug%"
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App

when@test:
  doctrine:
    dbal:
      # Si vous utilisez un suffixe pour le nom de la base de données de test, vous pouvez l'ajuster ici
      dbname_suffix: "_tomoki%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
